### ISSUE TITLE
Add namespace choice

### ISSUE THREAD

**Issue by jgournet** [sorry-cypress/charts#109]
## What is this feature about (1 sentence)
Add the possibility to install sorry-cypress in another namespace than default

**Comment by tico24** [comment]
The good news is you don't need any changes here. You just need to familiarise yourself with how Helm works.

See the `-n` or `--namespace` flag referenced in the Helm documentation we link to in our readme: https://helm.sh/docs/helm/helm_install/

And this line from our readme:
`helm install [RELEASE_NAME] sorry-cypress/sorry-cypress [flags]`

use the `-n` flag where we define `[flags]`
