### ISSUE TITLE
Default configuration doesn't work with in-memory database

### ISSUE THREAD

**Issue by igrlk** [sorry-cypress/charts#118]
## Summary

Hey guys. I'm trying to deploy the helm chart with default [values.yaml](https://github.com/sorry-cypress/charts/blob/main/charts/sorry-cypress/values.yaml) and getting the following error:
```
Failed to evaluate #
Run the proper check depending on the version [[ (mongo --version | grep "MongoDB shell") =~ ([0-9]+.[0-9]+.[0-9]+) ]] && VERSION={BASH_REMATCH[1]} . /opt/bitnami/scripts/libversion.sh VERSION_MAJOR="(get_sematic_version "VERSION" 1)" VERSION_MINOR="(get_sematic_version "VERSION" 2)" VERSION_PATCH="(get_sematic_version "VERSION" 3)" if [[ "VERSION_MAJOR" -ge 4 ]] && [[ "VERSION_MINOR" -ge 4 ]] && [[ "VERSION_PATCH" -ge 2 ]]; then mongo --disableImplicitSessions TLS_OPTIONS --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep -q 'true' else mongo --disableImplicitSessions TLS_OPTIONS --eval 'db.isMaster().ismaster || db.isMaster().secondary' | grep -q 'true' fi EL1012E: Cannot index into a null value

Deploy failed: Error from server (NotFound): error when creating "STDIN": namespaces "spinnaker" not found
```
<img width="491" alt="Screenshot 2022-05-08 at 19 20 35" src="https://user-images.githubusercontent.com/36277508/167303086-0b2bbd77-34b5-46ea-bcb8-0a48e03b38c7.png">

Looks like the director is trying to use mongodb though there is `executionDriver: "../execution/in-memory"` in values.yaml

## How to reproduce
Deploy the helm chart using the default [values.yaml](https://github.com/sorry-cypress/charts/blob/main/charts/sorry-cypress/values.yaml)

## Environment

- sorry-cypress version: `1.4.10`
- cypress version: `-`
- helm chart version: `3`

**Comment by tico24** [comment]
`Deploy the helm chart using the default values.yaml`

If you deploy the helm chart using the default values.yaml, you will get a mongodb database, because this is what's enabled by default. This suggests you have modified the values. Can you please include your full values modifications?

**Comment by igrlk** [comment]
Hi @tico24. I didn't make any modifications unfortunately :( 
Attaching the `values.yaml`, it's copied from **github** Attaching as txt since github doesn't allow `.yaml` to be uploaded
[values.txt](https://github.com/sorry-cypress/charts/files/8649878/values.txt)

**Comment by tico24** [comment]
If you didn't change anything, it indeed won't work. Your error is also complaining about a missing namespace. You don't set the namespace in the helm chart, that's external.

You'll need to modify the values yaml to add in various ingresses at a minimum.
