### ISSUE TITLE
Make AWS credentials optional

### ISSUE THREAD

**Issue by fsmaia** [sorry-cypress/charts#15]
As there are several ways to provide AWS authentication (credential files, environment variables, or even abstractions like kiam), we could make `director.s3.accessKeyId` and `director.s3.secretAccessKey` optional by having an empty default value and handling its presence on the deployment environment variables.

What do you think, @tico24 and @agoldis?

**Comment by agoldis** [comment]
I think that for power users that use helm, it would be trivial to understand the need to setup the variables. We can help then by placing a warning / note. Is there such an option in helm realm?

**Comment by tico24** [comment]
@agoldis only really by adding comments to the values.yml and/or documentation. This is the 'standard' way really. You're right though, most Helmists (it's a word!) would be comfortable with it anyway so it wouldn't be too scary.

@fsmaia While it's an admirable desire... I wonder if it's worth waiting for features like this to get requested before we extend the helm chart too far? (Unless you have a burning desire of course!)

**Comment by agoldis** [comment]
I am reading a tutorial  to become a cool Helmists 👀

**Comment by fsmaia** [comment]
I think we could still keep the current functionality and documentation, but only provisioning the `kind: Secret` if the `values.secretAccessKey` is different than `""`. Current the default value is `zyx`, and then we would change to `""`

**Comment by fsmaia** [comment]
Just needed to merge the change, but we could continue discussing here.

Do you guys think should have an authentication section on README or delegate it to https://sorry-cypress.dev like we already do?

Please reopen the issue if the merged solution is not okay or if we could enhance it somehow!

**Comment by tico24** [comment]
I think as much on the official site as possible.
