### ISSUE TITLE
Failure on redeploying the mongo service

### ISSUE THREAD

**Issue by fsmaia** [sorry-cypress/charts#18]
## Summary

When installing/updating the helm chart, it will update the mongo service deployment, which will scale a new pod, and downscale the old one when the new one is successful. When launching the new pod, it will try to bind the persistent volume, but at that time it is bound to the old one, and therefore the deployment fails.

## How to reproduce

Reinstalling/redeploying the helm chart.

## Environment

- sorry-cypress version: `0.6.1`
- cypress version: `6.2.1`
- helm chart version: `0.1.14`

**Comment by tico24** [comment]
ah yeh.. that will happen. oops!

Short term hacky workaround if anyone is immediately stuck would be to just delete the deployment prior to upgrading. (not nice but it works).

I'd imagine changing the mongo deployment into a StatefulSet will probably resolve the issue properly.

**Comment by tico24** [comment]
We should probably make sure the tests test this.

**Comment by fsmaia** [comment]
I'm on it. I have a doubt: if `mongo.persistence.enabled` is set to true so we must keep using the `Deployment` instead of `StatefulSet`?

**Comment by tico24** [comment]
Yeah, we'll have to I guess. Good shout.
