### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by fbritoferreira** [sorry-cypress/charts#194]
Seems like there havent been any updates since october, and a few prs are waiting for review

**Comment by agoldis** [comment]
I am not familiar enough with k8s  and others are busy. Are you willing to take a look at the PRs?s

**Comment by fbritoferreira** [comment]
@agoldis Sure I would be happy to do it

**Comment by agoldis** [comment]
Cool, I have added you to the contributors team
