### ISSUE TITLE
Wrong screenshot driver recommended for s3 storage setup

### ISSUE THREAD

**Issue by jwohlfahrt** [sorry-cypress/charts#199]
## Summary

Sorry cypress chart [README docs mention](https://github.com/sorry-cypress/charts/blob/main/charts/sorry-cypress/README.md#s3) if you are using s3 storage setup that you should use the mino screenshot driver, but seems like this is a typo, and the s3 screenshot driver should be recommended, unless I'm mistaken.

## How to reproduce

The readme docs in question can be found [here](https://github.com/sorry-cypress/charts/blob/main/charts/sorry-cypress/README.md#s3).

## Environment

- sorry-cypress version: `2.4.2`
- cypress version: `12.5.0`
- helm chart version: `1.9.0`

**Comment by fbritoferreira** [comment]
@jwohlfahrt Could you create a pr to fix this?

**Comment by jwohlfahrt** [comment]
@fbritoferreira for sure!
