### ISSUE TITLE
it still counting execution time when run timed out

### ISSUE THREAD

**Issue by renling-nd** [sorry-cypress/charts#207]
## Summary

![image](https://user-images.githubusercontent.com/87467252/230245722-488dabf7-4f7c-4d43-bb1c-1a5feb4557ce.png)

![2023 04 06_高仁玲 6c6a79669f73a151589288cbe3e3e327](https://user-images.githubusercontent.com/87467252/230245790-02ca2293-abdd-4a11-803e-ecf7df29723b.png)

I hope set spec duration max time to runs timeout, and stop to counting time, and status can set to "Untested"

Thanks!
## Environment

- sorry-cypress version: `2.5.3`
- cypress version: `9.7.0`
- helm chart version: `0.2.3`

**Comment by fbritoferreira** [comment]
Please post on https://github.com/sorry-cypress/sorry-cypress repo as this is the chart repo only
