### ISSUE TITLE
Minio port change

### ISSUE THREAD

**Issue by thowd22** [sorry-cypress/charts#208]
## Summary

Im deploying minio with the sorry-cypress chart and I realized my screenshots are not being saved to the bucket. I think its because port 9000 is hard coded in director and my minio runs through an ingress on port 80. There does not seem to be a way to override the MINIO_PORT in the values.yaml.

## How to reproduce
Deploy using helm on a kubernetes cluster with metallb as the load balancer. 

## Environment
- sorry-cypress version: `latest`
- cypress version: `8.7.0`
- helm chart version: `2.5.2`

**Comment by fbritoferreira** [comment]
@thowd22 You can update this by setting the servicePort option on minio config

```yaml
minio:
  service:
    port: 80
```
