### ISSUE TITLE
Add the possibility to use an already installed minio

### ISSUE THREAD

**Issue by yelhouti** [sorry-cypress/charts#54]
- [X] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Be able to use an already installed minio

## Why is it needed? What is the value? For whom do we build it?
The best way of installing minio is through the operator, if you already have minio installed you wouldn't want a new instance. It would be great to be able to use it.

**Comment by mlewiarz** [comment]
Yes, there should be possibiliy to set all minio related envs. We have minio outside k8s cluster. 
Even when we want to use internal provided by chart we can't use it because it adds port number to view url. 
At least add possibility to set MINIO_READ_URL_PREFIX vaiable.
Thanks

**Comment by erikmartino** [comment]
I suggest you add the possibility to set the s3 endpoint url and then use the s3 protocol to talk to the external minio.

**Comment by tico24** [comment]
PRs are welcome. This isn't something I will be taking on myself.

**Comment by cmutz** [comment]
Hello,
There is a PR here https://github.com/sorry-cypress/charts/pull/167
Regards,

**Comment by fbritoferreira** [comment]
Closing this issues has is no longer relevant
