### ISSUE TITLE
wrong construction of mongodb connection string, in case a replica set is used

### ISSUE THREAD

**Issue by SaulTigh77** [sorry-cypress/charts#57]
## Summary

The connection string for a mongodb replicaset is wrongly constructed, so that director and api can not connect to mongodb.
The most urgent thing is the hardcoded port information on the end of the connection string.

## How to reproduce

I want to use a pre-installed mongodb cluster, to get a  more reliable mongodb service, because i stumbled over the unsolved issue: https://github.com/sorry-cypress/sorry-cypress/issues/90

Therefore i installed a mongodb cluster with the bitnami chart (https://github.com/bitnami/charts/tree/master/bitnami/mongodb), setting the architecture to "replicaset" with 3 nodes (pods).

To gain high availability, the connection string for the nodejs mongodb client in my scenario needs to be:
`mongodb://k8s-sorry-cypress-mongo-mongodb-0.k8s-sorry-cypress-mongo-mongodb-headless.sorry-cypress.svc.cluster.local:27017,k8s-sorry-cypress-mongo-mongodb-1.k8s-sorry-cypress-mongo-mongodb-headless.sorry-cypress.svc.cluster.local:27017,k8s-sorry-cypress-mongo-mongodb-2.k8s-sorry-cypress-mongo-mongodb-headless.sorry-cypress.svc.cluster.local:27017/sorry-cypress?replicaSet=rs0` 

I put this string in the mongoServer parameter (with mongo.enabled=false) provided by the sorry-cypress chart.

But the MONGODB_URI in the deployments of api as well director is constructed as follows:
`mongodb://mongodb://k8s-sorry-cypress-mongo-mongodb-0.k8s-sorry-cypress-mongo-mongodb-headless.sorry-cypress.svc.cluster.local:27017,k8s-sorry-cypress-mongo-mongodb-1.k8s-sorry-cypress-mongo-mongodb-headless.sorry-cypress.svc.cluster.local:27017,k8s-sorry-cypress-mongo-mongodb-2.k8s-sorry-cypress-mongo-mongodb-headless.sorry-cypress.svc.cluster.local:27017/sorry-cypress?replicaSet=rs0:27017`

This isn't working. At least the hardcoded port information in the end of the string breaks it.

I edited the deployment manually within the cluster to the proper format - and it works.

So we need an option to pass a proper replicaset connection string.

## Environment

- helm chart version: `0.1.36`

**Comment by tico24** [comment]
v1+ of the helm chart installs that very mongodb chart. You have the option to deploy as a replicaset this way, and it _should_ just work. It's working on a 2-node replicaset in my production cluster. Give it a try and let me know.

**Comment by SaulTigh77** [comment]
Hi,
i tried the 1.0.0 chart and i really like the dependency to the bitnami/mongodb chart and all possibilities associated therewith.
Unfortunately the deployments of api and director still connecting (setting MONGODB_URI) only to the master pod of the mongodb replicaset. Therefore it is not high available.

I would like to have an additional optional parameter in the values.yaml, like `mongodb.mongoConnectionString`, which then is used (if not empty) instead of `mongodb://{{ include "mongodb.hostname" . }}:{{ .Values.mongodb.service.port }}`.

**Comment by tico24** [comment]
This should be addresses in chart ver 1.0.2
