### ISSUE TITLE
Conditional value prevents setting mongodb ENV variables necessary for external DB configuration

### ISSUE THREAD

**Issue by jonpham** [sorry-cypress/charts#58]
https://github.com/sorry-cypress/charts/blob/5290c43bf70a9be46bcfe340deb03b1ea7851289/charts/sorry-cypress/templates/deployment-api.yml#L38

When the helm chart value `mongodb.enabled == false`  the conditional on Line 38 prevents the MONGODB_DATABASE && MONGODB_URI ENV variables from being set to the sorry-cypress--api deployment object which prevents Helm Chart usage for users wanting to configure an external DB.

**Comment by tico24** [comment]
Should be resolved in release 1.0.1
