### ISSUE TITLE
Startup issue: "/var/cache/nginx/client_temp" failed (13: Permission denied)

### ISSUE THREAD

**Issue by xrow** [sorry-cypress/charts#61]
## Summary

Sorry cypress does not start pod sorry-cypress-dashboard, but should do start it

## How to reproduce

```
[root@openshift ~]# helm install my-release sorry-cypress/sorry-cypress -n xrow 
NAME: my-release
LAST DEPLOYED: Thu Jul  1 19:31:33 2021
NAMESPACE: xrow
STATUS: deployed
REVISION: 1
```

You now see this in the logs:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
--
  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
  | 10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
  | 20-envsubst-on-templates.sh: ERROR: /etc/nginx/templates exists, but /etc/nginx/conf.d is not writable
  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
  | /docker-entrypoint.sh: Configuration complete; ready for start up
  | 2021/07/01 17:31:55 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
  | nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
  | 2021/07/01 17:31:55 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
  | nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
```

## Environment

- sorry-cypress version: latest
- cypress version: latest
- platform: 
```
[root@openshift ~]# oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.06.xrow.net:8443
openshift v3.11.0+9caa622-494
kubernetes v1.11.0+d4cacc0
```
- service: `dashboard`

**Comment by tim-sendible** [comment]
This will likely be a container issue not a helm chart issue. 

K8s 1.11 is also unsupported I’m afraid.

**Comment by xrow** [comment]
I think the reason is that the container doesn`t support non-root users. That is a common security feature of opernshift and other setups. The helm chart aus you can see is fine since it installs so that chart is API 1.11 compatible.

**Comment by tim-sendible** [comment]
You need to raise an issue about non root containers in the product repo, not the helm one. I believe there already is an issue on the topic. 

Regardless of whether it works, we don’t support k8s 1.11.

**Comment by xrow** [comment]
;-) https://github.com/sorry-cypress/sorry-cypress/issues/391 they send me to you, but please close.

**Comment by tim-sendible** [comment]
Then I think we are missing context or information here. 

If you can demonstrate a (purely) helm issue on a cncf-supported kubernetes version then I’m happy to help.

**Comment by xrow** [comment]
Look at the other ticket and close this one :-). There is what you asked for. Else you can also implement a privileged option in your chart, but that will be a feature.
