### ISSUE TITLE
Director readiness probe isn't great

### ISSUE THREAD

**Issue by tico24** [sorry-cypress/charts#63]
`Warning  ProbeWarning  4m18s (x481 over 84m)  kubelet  Readiness probe warning: Found. Redirecting to https://github.com/agoldis/sorry-cypress`

**Comment by tico24** [comment]
tl;dr you can't have a http readiness probe checking for a redirect, it must get a 200 response.
So we should check for something else or not have one.

**Comment by tico24** [comment]
I have removed the probe for now to stop the flapping, but I'll leave this open for now... maybe there's a sensible exec command to use instead.

**Comment by Hackatosh** [comment]
Hello ! I think we could use the mongo db health check I implemented : https://github.com/sorry-cypress/sorry-cypress/pull/589

This way the director will be considered ready when the express server is listening and the connexion with MongoDB is working.

**Comment by tico24** [comment]
This would (obviously) only be a solution if the user has chosen to use a mongodb though.

**Comment by Hackatosh** [comment]
Then I think we should just implement an API health check like that respond a 200 if the API is running

**Comment by tico24** [comment]
Ah yeh. It's still technically possible.. you just don't get an API.

And `executionDriver: "../execution/in-memory"` is valid.

**Comment by tico24** [comment]
Sounds possible then. I probably can't get to this this week, will happily accept PRs :)

**Comment by tico24** [comment]
Resoved by PR #134
