### ISSUE TITLE
Director service always runs on port 1234

### ISSUE THREAD

**Issue by testworksau** [sorry-cypress/charts#90]
## Summary

We are using the Terraform helm provider. When specifying the following abbreviated configuration:

```
yamlencode({
      director = {
        service = {
          port = 4002
        }
})
```
The director service always starts on port `1234`. The same syntax allows the API and Dashboard service use the correct port.

I suspect this line:

https://github.com/sorry-cypress/charts/blob/4f3c41080ce689f0e05512370be7d22a3ad6ae7a/charts/sorry-cypress/templates/deployment-director.yml#L108

should be changed to:
```
- containerPort: {{ .Values.director.service.port }}
```

I am happy to raise a PR if my suspicion is correct 😃 

- sorry-cypress version: `2.1.1`
- cypress version: `N/A`
- helm chart version: `1.4.4`

**Comment by tico24** [comment]
That's definitely the issue, yes. A PR would be welcome :)

**Comment by testworksau** [comment]
Thanks for the prompt reply @tico24 - done!

**Comment by tico24** [comment]
Release 1.4.5 has your fix in it: https://github.com/sorry-cypress/charts/releases/tag/sorry-cypress-1.4.5
