### ISSUE TITLE
Disabling mongodb doesn't appear to allow the chart to be deployed

### ISSUE THREAD

**Issue by testworksau** [sorry-cypress/charts#91]
## Summary

We're using the helm terraform provider, and are attempting to disable the mongodb service. We're also using the `api`, `dashboard`, and `director` service.

A cut down version of our configuration is:

```
yamlencode({

      director = {
        environmentVariables = {
          executionDriver = "../execution/in-memory"
        }

      mongodb = {
        internal_db = {
          enabled = false
        }
      }
})
```

The deployment fails:

```
module.sorry-cypress.helm_release.sorry_cypress: Still creating... [4m50s elapsed]
module.sorry-cypress.helm_release.sorry_cypress: Still creating... [5m0s elapsed]

Warning: Helm release "sorry-cypress" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.

  with module.sorry-cypress.helm_release.sorry_cypress,
  on modules/sorry-cypress/chart.tf line 11, in resource "helm_release" "sorry_cypress":
  11: resource "helm_release" "sorry_cypress" {

Error: timed out waiting for the condition

  with module.sorry-cypress.helm_release.sorry_cypress,
  on modules/sorry-cypress/chart.tf line 11, in resource "helm_release" "sorry_cypress":
  11: resource "helm_release" "sorry_cypress" {

ERROR: 1
make: *** [deploy] Error 1
```

`helm list -n sorry-cypress` yields:
![image](https://user-images.githubusercontent.com/11973031/155072844-4ea28e69-0120-444b-a8c6-b72a69c40db1.png)

`kubectl get deployment -n sorry-cypress` yields:
![image](https://user-images.githubusercontent.com/11973031/155072772-72ba9865-b247-477b-aaee-e87acbb070ca.png)

The docs seem to indicate it is possible to run without mongodb (not that we want to do that long term) so I'm wondering if you can provide any guidance as to where I should be looking to resolve this issue.

## Environment

- sorry-cypress version: `2.1.1`
- cypress version: `N/A`
- helm chart version: `1.4.4`

**Comment by tico24** [comment]
The issue will lie somewhere around here, but I'm not in a position to investigate and fix in the short term: https://github.com/sorry-cypress/charts/blob/main/charts/sorry-cypress/templates/deployment-api.yml#L38-L48

**Comment by tico24** [comment]
Actually, it's been a while. I think if you run the API you must have mongo set up. Can you confirm @agoldis?

**Comment by agoldis** [comment]
confirming

**Comment by tico24** [comment]
Nice one, thanks @agoldis 

@testworksau I have added some quick notes to the values.yaml to hopefully prevent this confusion in the future.

**Comment by testworksau** [comment]
Cool, thanks @tico24 - your changes to the values.yaml file make sense and I can confirm they would have helped alleviate my confusion in this instance 👍🏼
